Base of the DstController implemented ;fixes #18
RHEAGROUP/DEH-MATLAB pull request #22
Opened 2022-01-24 13:49 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-MATLAB/pulls) open
- [x] I have verified that I am following the DEHP-MATLAB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-MATLAB/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #18 
- Connection to Matlab via COM Interop
- Disconnection from Matlab

2022-01-24 13:50 UTC, antoineatrhea commented
![image](https://user-images.githubusercontent.com/97221392/150794850-0367878b-93bb-4055-b074-16b5afa353d9.png)

2022-01-25 09:40 UTC, alexatrhea requested changes
Several small changes requested.

2022-01-25 09:40 UTC, alexatrhea commented on DEHPMatlab/ViewModel/DataSourceViewModel.cs
> +        public IStatusBarControlViewModel StatusBar { get; set; }
Missing docs

2022-01-25 09:40 UTC, alexatrhea commented on DEHPMatlab/ViewModel/MainWindowViewModel.cs
> +        public IDstDataSourceViewModel DstDataSourceViewModel { get; }
Missing docs

2022-01-25 09:40 UTC, alexatrhea commented on DEHPMatlab/ViewModel/Row/RowViewModel.cs
> +    public class RowViewModel: ReactiveObject
Maybe a bit more specific classname like "MatlabWorspaceValueRowViewModel"? Very generic right now.

2022-01-25 09:40 UTC, alexatrhea commented on DEHPMatlab/ViewModel/Row/RowViewModel.cs
> +        private object value;
We typically group all privates on top of the file, then constructors then the public props.

2022-01-25 11:06 UTC, nathanatrhea requested changes
Doc changes requested

2022-01-25 11:06 UTC, nathanatrhea commented on DEHPMatlab/DstController/DstController.cs
> +        /// </summary>
missing doc for the param

2022-01-25 11:06 UTC, nathanatrhea commented on DEHPMatlab/Services/MatlabConnector/MatlabConnector.cs
> +        /// <param name="variableName">The name of the varible</param>
misspelled *varible

2022-01-25 11:06 UTC, nathanatrhea commented on DEHPMatlab/ViewModel/DataSourceViewModel.cs
> +        protected string DataSourceName;
missing doc

2022-01-25 11:06 UTC, nathanatrhea commented on DEHPMatlab/ViewModel/DataSourceViewModel.cs
> +        protected void UpdateStatusBar(bool isSessionOpen)
missing doc

2022-01-25 11:06 UTC, nathanatrhea commented on DEHPMatlab/ViewModel/MainWindowViewModel.cs
>  }
missing end of file empty line

2022-01-25 12:24 UTC, alexatrhea approved these changes

2022-01-25 12:27 UTC, nathanatrhea approved these changes

2022-01-25 12:37 UTC, merged