Parsing Matlab code done : fixes #19
RHEAGROUP/DEH-MATLAB pull request #23
Opened 2022-01-26 15:39 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-MATLAB/pulls) open
- [x] I have verified that I am following the DEHP-MATLAB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-MATLAB/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fixes #19 
- Matlab script can be parse
- Auto detection of simple inputs
- Populate the Matlab Workspace with the inputs
- Modification of these inputs
- Run the script with the new inputs

Thanks to https://github.com/mahalex/MParser for the dll

2022-01-26 17:29 UTC, alexatrhea approved these changes

2022-01-26 17:29 UTC, alexatrhea commented
Please post code coverage stats.

2022-01-27 07:32 UTC, antoineatrhea commented
![image](https://user-images.githubusercontent.com/97221392/151311955-268f1bd6-2067-4d49-b0b5-8b1691e4eb24.png)

2022-01-28 09:18 UTC, nathanatrhea requested changes

2022-01-28 09:18 UTC, nathanatrhea commented on DEHPMatlab/Services/MatlabParser/MatlabParser.cs
> +            var filePath = $"{directoryName}\\f{DateTime.Now:yyyyMMddHHmmss}.m";
Please use Path.Combine when dealing with paths

2022-01-28 09:33 UTC, nathanatrhea approved these changes

2022-01-28 09:34 UTC, merged