Mapping dialog from hub to dst implemented: fixes #29
RHEAGROUP/DEH-MATLAB pull request #34
Opened 2022-02-08 12:03 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-MATLAB/pulls) open
- [x] I have verified that I am following the DEHP-MATLAB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-MATLAB/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

#29 
- Mapping rule changed to follow the desired behavior
- Mapping dialog from hub to dst has been implemented

2022-02-08 13:12 UTC, alexatrhea approved these changes

2022-02-08 22:29 UTC, nathanatrhea requested changes

2022-02-08 22:29 UTC, nathanatrhea commented on DEHPMatlab/ViewModel/Dialogs/HubMappingConfigurationDialogViewModel.cs
> +
extra space

2022-02-09 07:38 UTC, nathanatrhea approved these changes

2022-02-09 07:40 UTC, merged