"mapped element" Added : Fix #82
RHEAGROUP/DEH-MATLAB pull request #83
Opened 2022-06-03 13:31 UTC by antoineatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/DEHP-MATLAB/pulls) open
- [x] I have verified that I am following the DEHP-MATLAB [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/DEHP-MATLAB/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description

Fix #82 
- Update the "Select all" / "Deselect all" to "Select all mapped element" / "Deselect all mapped element"  on both ImpactView panel

2022-06-03 15:14 UTC, alexatrhea requested changes
same comment for all strings. Use plural form.

2022-06-03 15:14 UTC, alexatrhea commented on DEHPMatlab/ViewModel/NetChangePreview/DstNetChangePreviewViewModel.cs
> +                new ContextMenuItemViewModel("Select all mapped element for transfer", "", this.SelectAllCommand, MenuItemKind.Copy, ClassKind.NotThing));
element**s**

2022-06-04 08:10 UTC, alexatrhea approved these changes

2022-06-07 12:04 UTC, nathanatrhea approved these changes

2022-06-07 12:07 UTC, merged